name: "Deploy CloudFormation Stack"
on: 
  push:
    branches:
    - master

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: mgenteluci/cloudformation-deploy-action@v1.3.0
      env:
        TEMPLATE: './template.yaml'
        CAPABILITIES: CAPABILITY_NAMED_IAM
        AWS_STACK_NAME: 'website-user-production'
        AWS_REGION: 'ap-southeast-2'
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEPLOY_BUCKET: ${{secrets.AWS_DEPLOY_BUCKET}}
        PARAMETER_OVERRIDES: CertificateArn=arn:aws:acm:us-east-1:740876047172:certificate/3275d435-4981-4ed7-b690-fcb81320b4ee EnvironmentName=production HostedZoneUrl=thoud.co ServiceName=auth UserPoolId=ap-southeast-2_nC0RxIg6O 
